FROM python:3.7-buster

WORKDIR /app/
COPY ./pumps/ /app/pumps/
COPY requeriments.txt /app/
RUN pip install --no-cache-dir -r requeriments.txt

CMD [ "python", "pumps/manage.py", "runserver", "0.0.0.0:8080"]