FROM python:3.7-buster

WORKDIR /app/
COPY ./pumps/ /app/pumps/
COPY requeriments.txt /app/
RUN pip install --no-cache-dir -r requeriments.txt
COPY docker-entrypoint.sh /app/
RUN chmod +x docker-entrypoint.sh

#CMD [ "python", "pumps/manage.py", "runserver", "0.0.0.0:8080"]
ENTRYPOINT [ "./docker-entrypoint.sh" ]