version: "3"

services:
  db:
    container_name: db
    image: "postgres:9.5"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    hostname: psql
    #network_mode: host #Set the host's network
    
  app:
    container_name: app
    restart: always
    image: "pumps:v0.0.1"
    ports:
      - "8080:8080"
    #network_mode: host #Set the host's network