version: "3"

services:
  db:
    container_name: db
    image: "postgres:9.5"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    hostname: psql
    volumes:
      - pumps:/var/lib/postgresql/data/
    #network_mode: host #Set the host's network
    
  app:
    container_name: app
    restart: always
    image: "pumps:v0.0.1"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    #network_mode: host #Set the host's network

volumes:
  pumps:

# Only if you already create the volume with: $docker volume create pumps
#volumes:
#  pumps:
#    external: true